Add components to OpenAPI spec
Convert json schema to components. The json schema is needed to generate classes but OpenAPI spec within SwaggerHub will not behave as expected when componenents are in a seperate file

diff --git a/.github/workflows/ci-draft.yml b/.github/workflows/ci-draft.yml
--- a/.github/workflows/ci-draft.yml
+++ b/.github/workflows/ci-draft.yml
@@ -45,9 +45,11 @@ jobs:
           echo "draft_version=$DRAFT_VERSION"
           echo "draft_version=$DRAFT_VERSION" >> $GITHUB_OUTPUT
 
-  Update-Spec-Version:
-    needs: [Artefact-Version]
+  Modify-API-Spec:
+    needs: [ Artefact-Version ]
     runs-on: ubuntu-latest
+    env:
+      JSON_SCHEMA_FILENAME: "judges.json"
     outputs:
       openapi_file: ${{ steps.find_spec.outputs.openapi_file }}
     steps:
@@ -64,7 +66,14 @@ jobs:
           fi
           echo "openapi_file=$FILE" >> $GITHUB_OUTPUT
 
-      - name: Update info.version in OpenAPI spec using yq
+      - name: Check Json schema exists
+        run: |
+          if [ ! -f "${FILE_PATH_OPENAPI}/schema/${JSON_SCHEMA_FILENAME}" ]; then
+            echo "❌ Json schema not found. Failing build."
+            exit 1
+          fi
+
+      - name: Update OpenAPI info.version and inject Judges schema
         env:
           API_NAME: ${{ github.event.repository.name }}
           API_VERSION: ${{ needs.Artefact-Version.outputs.draft_version }}
@@ -73,20 +82,21 @@ jobs:
           cmd: |
             yq '
               .info.version = strenv(API_VERSION) |
-              .servers[0].url = "https://virtserver.swaggerhub.com/HMCTS-DTS/" + strenv(API_NAME) + "/" + strenv(API_VERSION)
+              .servers[0].url = "https://virtserver.swaggerhub.com/HMCTS-DTS/" + strenv(API_NAME) + "/" + strenv(API_VERSION) |
+              .components.schemas.Judges = load("${FILE_PATH_OPENAPI}/schema/${JSON_SCHEMA_FILENAME}")
             ' "${{ steps.find_spec.outputs.openapi_file }}" > openapi-versioned.yml
 
       - name: Replace original OpenAPI file
         run: mv openapi-versioned.yml "${{ steps.find_spec.outputs.openapi_file }}"
 
-      - name: Upload updated OpenAPI file
+      - name: Upload updated OpenAPI spec
         uses: actions/upload-artifact@v4
         with:
           name: updated-openapi-spec
           path: ${{ steps.find_spec.outputs.openapi_file }}
 
   Build:
-    needs: [Artefact-Version, Update-Spec-Version]
+    needs: [Artefact-Version, Modify-API-Spec]
     runs-on: ubuntu-latest
 
     steps:
diff --git a/.github/workflows/push-draft-openapi-spec.yml b/.github/workflows/push-draft-openapi-spec.yml
--- a/.github/workflows/push-draft-openapi-spec.yml
+++ b/.github/workflows/push-draft-openapi-spec.yml
@@ -31,18 +31,18 @@ jobs:
           echo "draft_version=$DRAFT_VERSION"
           echo "draft_version=$DRAFT_VERSION" >> $GITHUB_OUTPUT
 
-  Apply-Version-to-API-Spec:
+  Modify-API-Spec:
     needs: [API-Version]
     runs-on: ubuntu-latest
-
+    env:
+      FILE_PATH_OPENAPI: "src/main/resources/openapi"
+      JSON_SCHEMA_FILENAME: "judges.json"
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
 
       - name: Find OpenAPI file
         id: find_spec
-        env:
-          FILE_PATH_OPENAPI: "src/main/resources/openapi"
         run: |
           FILE=$(find "${FILE_PATH_OPENAPI}" -name "*.openapi.yml" | head -n 1)
           if [ -z "$FILE" ]; then
@@ -51,7 +51,14 @@ jobs:
           fi
           echo "openapi_file=$FILE" >> $GITHUB_OUTPUT
 
-      - name: Update info.version in OpenAPI spec using yq
+      - name: Check Json schema exists
+        run: |
+          if [ ! -f "${FILE_PATH_OPENAPI}/schema/${JSON_SCHEMA_FILENAME}" ]; then
+            echo "❌ Json schema not found. Failing build."
+            exit 1
+          fi
+
+      - name: Update OpenAPI info.version and inject Judges schema
         env:
           API_NAME: ${{ github.event.repository.name }}
           API_VERSION: ${{ needs.API-Version.outputs.draft_version }}
@@ -60,7 +67,8 @@ jobs:
           cmd: |
             yq '
               .info.version = strenv(API_VERSION) |
-              .servers[0].url = "https://virtserver.swaggerhub.com/HMCTS-DTS/" + strenv(API_NAME) + "/" + strenv(API_VERSION)
+              .servers[0].url = "https://virtserver.swaggerhub.com/HMCTS-DTS/" + strenv(API_NAME) + "/" + strenv(API_VERSION) |
+              .components.schemas.Judges = load("${FILE_PATH_OPENAPI}/schema/${JSON_SCHEMA_FILENAME}")
             ' "${{ steps.find_spec.outputs.openapi_file }}" > openapi-versioned.yml
 
       - name: Upload versioned OpenAPI spec
@@ -70,7 +78,7 @@ jobs:
           path: openapi-versioned.yml
 
   Push-API-to-APIHub:
-    needs: [API-Version, Apply-Version-to-API-Spec]
+    needs: [API-Version, Modify-API-Spec]
     runs-on: ubuntu-latest
     env:
       SWAGGERHUB_API_KEY: ${{ secrets.APIHUB_API_KEY }}
